/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DesignSystemLacunasRouteImport } from './routes/design-system.lacunas'
import { Route as LabHeroAnimationRouteImport } from './routes/lab.hero-animation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemLacunasRoute = DesignSystemLacunasRouteImport.update({
  id: '/lacunas',
  path: '/lacunas',
  getParentRoute: () => DesignSystemRoute,
} as any)
const LabHeroAnimationRoute = LabHeroAnimationRouteImport.update({
  id: '/lab/hero-animation',
  path: '/lab/hero-animation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRouteWithChildren
  '/design-system/lacunas': typeof DesignSystemLacunasRoute
  '/lab/hero-animation': typeof LabHeroAnimationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRouteWithChildren
  '/design-system/lacunas': typeof DesignSystemLacunasRoute
  '/lab/hero-animation': typeof LabHeroAnimationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRouteWithChildren
  '/design-system/lacunas': typeof DesignSystemLacunasRoute
  '/lab/hero-animation': typeof LabHeroAnimationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/design-system' | '/design-system/lacunas' | '/lab/hero-animation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design-system' | '/design-system/lacunas' | '/lab/hero-animation'
  id:
    | '__root__'
    | '/'
    | '/design-system'
    | '/design-system/lacunas'
    | '/lab/hero-animation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRoute: typeof DesignSystemRouteWithChildren
  LabHeroAnimationRoute: typeof LabHeroAnimationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/lacunas': {
      id: '/design-system/lacunas'
      path: '/lacunas'
      fullPath: '/design-system/lacunas'
      preLoaderRoute: typeof DesignSystemLacunasRouteImport
      parentRoute: typeof DesignSystemRoute
    }
    '/lab/hero-animation': {
      id: '/lab/hero-animation'
      path: '/lab/hero-animation'
      fullPath: '/lab/hero-animation'
      preLoaderRoute: typeof LabHeroAnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DesignSystemRouteChildren {
  DesignSystemLacunasRoute: typeof DesignSystemLacunasRoute
}

const DesignSystemRouteChildren: DesignSystemRouteChildren = {
  DesignSystemLacunasRoute: DesignSystemLacunasRoute,
}

const DesignSystemRouteWithChildren = DesignSystemRoute._addFileChildren(
  DesignSystemRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRoute: DesignSystemRouteWithChildren,
  LabHeroAnimationRoute: LabHeroAnimationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
