export { IconBase, type IconProps } from "./Icon";

export {
  IconSparkle,
  IconArrowRight,
  IconCheck,
  IconPlus,
  IconMinus,
  IconChevronLeft,
  IconChevronRight,
  IconStar,
  IconAccount,
  IconClose,
  IconAsterisk,
  IconGiftBox,
  IconMail,
  IconPhone,
  IconCalendar,
  IconBasket,
  IconLock,
  IconMapPin,
  IconPackage,
  IconTruck,
  IconCreditCard,
  IconPix,
  IconArrowLeft,
  IconChevronUp,
  IconChevronDown,
  IconBarcode,
  IconWallet,
  IconCopy,
  IconClock,
  IconHeadset,
  IconExternal,
} from "./ui";

export {
  IconOitavario,
  IconNovenaImaculada,
  IconSeteDomingosSaoJose,
  IconAniversarios,
  IconTrisagio,
  IconOutrasDatas,
} from "./liturgical";
